services:

  consul:
    image: hashicorp/consul:1.18.1
    hostname: consul
    ports:
      - "8500:8500"

  consul-populate:
    image: frogdevelopment/consul-populate:1.0.0-SNAPSHOT
    environment:
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
      CONSUL_KV_PREFIX: frog
      CONSUL_KV_VERSION: 1.2.3
      CONSUL_FILES_FORMAT: YAML
      CONSUL_FILES_TARGET: dev
      CONSUL_FILES_ROOT_PATH: /configurations
    volumes:
      - ./src/test/resources/files:/configurations:ro
