apiVersion: batch/v1
kind: Job
metadata:
  name: consul-populate
spec:
  template:
    spec:
      containers:
        - name: consul-populate
          image: xxxxxxx
          command: [ "","","" ]
          imagePullPolicy: Always
      restartPolicy: Never
  backoffLimit: 3
