apiVersion: batch/v1
kind: Job
metadata:
  name: consul-populate
spec:
  template:
    spec:
      automountServiceAccountToken: false
      containers:
        - name: consul-populate
          image: frogdevelopment/consul-populate:1.0.0
          args:
            - "consul.host=consul-svc"
            - "consul.port=8500"
            - "consul.kv.prefix=frog"
            - "consul.kv.version=1.2.3"
            - "consul.files.format=YAML"
            - "consul.files.target=dev"
            - "consul.files.root-path=/configurations"
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /configurations
              name: configurations
      restartPolicy: Never
      volumes:
        - name: configurations
          persistentVolumeClaim:
            claimName: configurationsPVC
            readOnly: true
  backoffLimit: 3
